### ISSUE TITLE
构建报错了

### ISSUE THREAD

**Issue by liupeng110112** [ruanyf/react-babel-webpack-boilerplate#18]
ERROR in ./~/css-loader!./app/components/App.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/liupeng/frontEnd/react-babel-webpack-boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/liupeng/frontEnd/react-babel-webpack-boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/liupeng/frontEnd/react-babel-webpack-boilerplate/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/liupeng/frontEnd/react-babel-webpack-boilerplate/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/components/App.css 4:14-77 13:2-17:4 13:2-17:4 14:20-83

这是怎么回事 @ruanyf 老师 谢谢！！

**Comment by ruanyf** [comment]
Node版本太老
