### ISSUE TITLE
Lint is broken

### ISSUE THREAD

**Issue by QuentinRoy** [ruanyf/react-babel-webpack-boilerplate#26]
eslint-config-airbnb latest version is broken with current eslint-plugin-* dev dependencies saved in `package.json`.

```ShellSession
$ npm run lint

> react-babel-webpack-boilerplate@1.2.2 lint /Users/quentinroy/Workspace/react-babel-webpack-boilerplate
> eslint 'app/**/*.@(js|jsx)'

/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint-config-airbnb-base/rules/imports.js:
	Configuration for rule "import/no-unresolved" is invalid:
	Value "data["0"].caseSensitive" has additional properties.

Referenced from: /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint-config-airbnb-base/index.js
Referenced from: eslint-config-airbnb
Referenced from: /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/.eslintrc
Error: /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint-config-airbnb-base/rules/imports.js:
	Configuration for rule "import/no-unresolved" is invalid:
	Value "data["0"].caseSensitive" has additional properties.

Referenced from: /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint-config-airbnb-base/index.js
Referenced from: eslint-config-airbnb
Referenced from: /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/.eslintrc
    at validateRuleOptions (/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-file.js:522:19)
    at /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-file.js:529:22)
    at /Users/quentinroy/Workspace/react-babel-webpack-boilerplate/node_modules/eslint/lib/config/config-file.js:391:36
```

Running 
```shell
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```
(from [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)) updates these dependencies and solves the issue but linting won't work anymore:

```ShellSession
$ npm run lint

> react-babel-webpack-boilerplate@1.2.2 lint /Users/quentinroy/Workspace/react-babel-webpack-boilerplate
> eslint 'app/**/*.@(js|jsx)'


/Users/quentinroy/Workspace/react-babel-webpack-boilerplate/app/main.jsx
  3:17  error  Unexpected use of file extension "jsx" for "./components/App.jsx"  import/extensions
  7:3   error  'document' is not defined                                          no-undef
  7:29  error  'document' is not defined                                          no-undef
```

Error 2 and 3 are easily fixed by adding `"browser": true` as an env in `.eslintrc`. However, I have not been able to fix the "jsx" extension issue even by using the appropriate [`import/extensions`](https://github.com/benmosher/eslint-plugin-import#importextensions) settings as specified by [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) except by fully disabling the rule.

**Comment by ruanyf** [comment]
Thanks for the reminder. I've updated `eslint-plugin-eslint` to the latest version and fixed the bug.

Please update the code.

```bash
$ git pull
$ rm -rf node_modules
$ npm install
``` 

It should work now.
