### ISSUE TITLE
Run Failed with branch webpack2

### ISSUE THREAD

**Issue by xiayy860612** [ruanyf/react-babel-webpack-boilerplate#52]
when I execute `npm start` with branch **webpack2**, it failed with below info:

```
> webpack-dev-server --devtool eval --progress --hot --content-base app

✖ ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unk
nownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-babel-webpack-boilerplate@1.4.1 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
npm ERR! Exit status 1
```

debug log info below:
```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v10.15.3-linux-x64/bin/node',
1 verbose cli   '/opt/node-v10.15.3-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-babel-webpack-boilerplate@1.4.1~prestart: react-babel-webpack-boilerplate@1.4.1
6 info lifecycle react-babel-webpack-boilerplate@1.4.1~start: react-babel-webpack-boilerplate@1.4.1
7 verbose lifecycle react-babel-webpack-boilerplate@1.4.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-babel-webpack-boilerplate@1.4.1~start: PATH: /opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:xxxxxxx/web/node_modules/.bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/opt/node-v10.15.3-linux-x64/bin:/home/user/.pyenv/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle react-babel-webpack-boilerplate@1.4.1~start: CWD: xxxxxxx/web
10 silly lifecycle react-babel-webpack-boilerplate@1.4.1~start: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --devtool eval --progress --hot --content-base app' ]
11 silly lifecycle react-babel-webpack-boilerplate@1.4.1~start: Returned: code: 1  signal: null
12 info lifecycle react-babel-webpack-boilerplate@1.4.1~start: Failed to exec start script
13 verbose stack Error: react-babel-webpack-boilerplate@1.4.1 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid react-babel-webpack-boilerplate@1.4.1
15 verbose cwd xxxxxxx/web
16 verbose Linux 4.15.0-50-generic
17 verbose argv "/opt/node-v10.15.3-linux-x64/bin/node" "/opt/node-v10.15.3-linux-x64/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error react-babel-webpack-boilerplate@1.4.1 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
22 error Exit status 1
23 error Failed at the react-babel-webpack-boilerplate@1.4.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Could you have a check with it?

**Comment by xiayy860612** [comment]
currently package.json include "webpack": "latest", it will use webpack v4 which is not compatible with v2

**Comment by ruanyf** [comment]
The repo is outdated, so I archived it.

P.S., it needs Webpack 1.x。https://github.com/ruanyf/react-babel-webpack-boilerplate/blob/master/package.json#L50
